import Vue from 'vue';
import {
    Button,
    NavBar,
    Tabbar,
    TabbarItem,
    Swipe,
    SwipeItem,
    Panel,
    Icon,
    SwipeCell,
    Card,
    SubmitBar,
    Checkbox,
    Col,
    Row,
    Stepper,
    Notify,
    CheckboxGroup,
    List,
    Cell,
    AddressEdit,
    Toast,
    AddressList,
    Search,
    Tag,
    ImagePreview,
    CouponCell,
    CouponList,
    Popup,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Tab,
    Tabs,
    CellGroup,
    TreeSelect,
    GridItem,
    Lazyload,
    Grid, 
    Image,
} from 'vant';

import 'vant/lib/index.css';

Vue.use(Button);
Vue.use(NavBar);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Panel);
Vue.use(Icon);
Vue.use(SwipeCell);
Vue.use(Card);
Vue.use(SubmitBar);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Col);
Vue.use(Row);
Vue.use(Stepper);
Vue.use(Notify);
Vue.use(List);
Vue.use(Cell);
Vue.use(AddressEdit);
Vue.use(Toast);
Vue.use(AddressList);
Vue.use(Search)
Vue.use(Row)
Vue.use(Col)
Vue.use(List)
Vue.use(Cell)
Vue.use(Icon)
Vue.use(SwipeCell)
Vue.use(Card)
Vue.use(Toast)
Vue.use(Tag)
Vue.use(ImagePreview)
Vue.use(CouponCell)
Vue.use(CouponList)
Vue.use(Popup)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(CellGroup)

Vue
    .use(Button)
    .use(NavBar)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Swipe)
    .use(SwipeItem)
    .use(TreeSelect)
    .use(Grid)
    .use(GridItem)
    .use(Card)
    .use(Toast);

Vue
.use(Button)
.use(NavBar)
.use(Tabbar)
.use(TabbarItem)
.use(Swipe)
.use(SwipeItem)
.use(Lazyload)
.use(Grid)
.use(GridItem)
.use(Image)
.use(Col)
.use(Row)

